FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt jupyterlab
COPY . /app
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port", "8888", "--no-browser", "--allow-root"]
