# yaml-language-server: $schema=./task-schema.json
id: PM-06
title: Schedule and Conduct Final Alignment Meeting
owner: product
depends_on: []
state: PLANNED
priority: MEDIUM
estimation_hours: 2
description: "Task PM-06: Schedule and Conduct Final Alignment Meeting"
artefacts:
  - docs/sprint/pre-sprint0-alignment.md
context_topics:
  - project-overview
