# yaml-language-server: $schema=./task-schema.json
id: TL-04
title: Verify Next.js Project Structure
owner: technical
depends_on:
  - TL-01
state: PLANNED
priority: MEDIUM
estimation_hours: 2
description: "Task TL-04: Verify Next.js Project Structure"
artefacts:
  - docs/setup/project-structure.md
context_topics:
  - infrastructure
  - ci-cd
  - tech-standards
