# yaml-language-server: $schema=./task-schema.json
id: TL-10
title: Verify RLS Policies for Supabase
owner: technical
depends_on:
  - TL-09
state: PLANNED
priority: MEDIUM
estimation_hours: 2
description: "Task TL-10: Verify RLS Policies for Supabase"
artefacts:
  - docs/setup/supabase-rls.md
context_topics:
  - infrastructure
  - ci-cd
  - tech-standards
